source = 'github_practice-person'

guard :shell do
  watch(/^#{source}.org$/) do |m|
#    %x{emacs #{source}.slide.org -batch -l org-init.el -f org-beamer-export-to-pdf}
    %x{emacs #{source}.handout.org -batch -l org-init.el -f org-latex-export-to-pdf}
  end

  watch(/^#{source}.handout.org$/) do |m|
    %x{emacs #{source}.handout.org -batch -l org-init.el -f org-latex-export-to-pdf}
  end

  watch(/^#{source}.slide.org$/) do |m|
    %x{emacs #{source}.slide.org -batch -l org-init.el -f org-beamer-export-to-pdf}
  end
end
